title: KubeLabs
description: A Curated List of Kubernetes Labs and Tutorials
baseurl: ""
url: "https://kubelabs.ajeetraina.com"
repository: ajeetraina/kubelabs

plugins:
  - jekyll-sitemap

include:
  - assets
  - CNAME