apiVersion: v1
kind: Pod
metadata:
  name: with-resources
  namespace: quota-demo
spec:
  containers:
  - name: nginx
    image: nginx:latest
    resources:
      requests:
        memory: "512Mi"
        cpu: "500m"
      limits:
        memory: "1Gi"
        cpu: "1"
