name: Deploy KubeLabs

on:
  push:
    branches: [ master, main ]
  pull_request:
    branches: [ master, main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      
      - name: Create required directories and clean existing docs
        run: |
          mkdir -p docusaurus/static/img
          # Clean out docs directory to avoid issues with old files
          rm -rf docusaurus/docs
          mkdir -p docusaurus/docs
      
      - name: Install dependencies
        run: |
          cd docusaurus
          npm install
      
      - name: Create placeholder logo
        run: |
          # Create a basic placeholder if the logo doesn't exist
          if [ ! -f docusaurus/static/img/kubernetes-logo.png ]; then
            echo "Creating placeholder logo"
            # Use a public URL for a sample logo
            curl -o docusaurus/static/img/kubernetes-logo.png https://raw.githubusercontent.com/kubernetes/kubernetes/master/logo/logo.png || echo "Could not download logo, but continuing"
          fi
      
      - name: Run content migration script
        run: |
          cd docusaurus
          node scripts/migrate-content.js
          
      - name: Flatten docs directory structure
        run: |
          cd docusaurus
          node scripts/flatten-docs.js
          
      - name: Fix title issues
        run: |
          cd docusaurus
          node scripts/fix-titles.js
      
      - name: List generated files (for debugging)
        run: |
          find docusaurus/docs -type f | sort
          echo "---"
          cat docusaurus/sidebars.js
      
      - name: Build site
        run: |
          cd docusaurus
          npm run build
      
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docusaurus/build
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'
      
      - name: Build and push Docker image
        if: github.event_name != 'pull_request'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo $GITHUB_TOKEN | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker build -t ghcr.io/${{ github.repository_owner }}/kubelabs:latest -f docusaurus/Dockerfile .
          docker push ghcr.io/${{ github.repository_owner }}/kubelabs:latest
